### ISSUE TITLE
Generar pipeline y despliegue para api movimientos_contables_mid

### ISSUE THREAD

**Issue by JocoolQ** [udistrital/movimientos_contables_mid#4]
- [x] Analizar requisitos para despliegue de API
 - [x] Generar entrypoint.sh para ejecución del compilado de API 
 - [x] Generar Dockerfile para despliegue de API en AWS
 - [x] Crear rama release/0.0.1
 - [x] Realizar merge de la rama develop con release/0.0.1
 - [x] Verificar funcionamiento de API

**Comment by criss201x** [comment]
Link de solicitud de despliegue en [Tuleap](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=40883)
